# Generated by Django 3.0.6 on 2020-12-26 00:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('typeCompany', models.CharField(choices=[('1', 'Todos'), ('2', 'Personal Interno'), ('3', 'Invitado')], max_length=1, verbose_name='Tipo Empresa')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
            },
        ),
        migrations.CreateModel(
            name='DetailEventAttend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dateTime_joined', models.DateTimeField(blank=True, null=True, verbose_name='Fecha  y hora de ingreso')),
                ('dateTime_out', models.DateTimeField(blank=True, null=True, verbose_name='Fecha  y hora de salida')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='induccion.Attendant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expositor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Expositor',
                'verbose_name_plural': 'Expositores',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=60, verbose_name='Tema')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
                ('aforo', models.PositiveIntegerField(verbose_name='Aforo')),
                ('public', models.CharField(choices=[('1', 'Todos'), ('2', 'Personal Interno'), ('3', 'Invitado')], max_length=1, verbose_name='Público')),
                ('DateIni', models.DateTimeField(verbose_name='Fecha Inicio Programada')),
                ('dateEndProgram', models.DateTimeField(verbose_name='Fecha Fin Programada')),
                ('dateEndReal', models.DateTimeField(blank=True, null=True, verbose_name='Fecha fin Real')),
                ('duration', models.CharField(blank=True, max_length=40, null=True, verbose_name='Duración')),
                ('state', models.CharField(choices=[('1', 'Registrado'), ('2', 'En Curso'), ('3', 'Terminado')], max_length=1, verbose_name='Estado')),
                ('token', models.TextField(blank=True, null=True)),
                ('attend', models.ManyToManyField(through='induccion.DetailEventAttend', to='induccion.Attendant')),
                ('expositor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='induccion.Expositor')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.AddField(
            model_name='detaileventattend',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='induccion.Event'),
        ),
    ]
